# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: env-replacer
builds:
  - id: env-replacer
    binary: env-replacer
    main: cmd/main.go
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

changelog:
  sort: desc

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      darwin: macOS

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: guumaster
    name: env-replacer

nfpms:
  - id: env-replacer
    builds:
      - env-replacer
    formats:
      - deb
    vendor: Guumaster
    homepage: https://github.com/guumaster/env-replacer
    maintainer: guumaster <guuweb@gmail.com>
    description: remove forgotten folders quick and easy
